[package]

name = "openssl"
version = "0.0.0"
authors = ["Steven Fackler <sfackler@gmail.com"]

[lib]

name = "openssl"
path = "src/lib.rs"

[features]
sslv2 = []
thread_id = []
tlsv1_2 = []
tlsv1_1 = []
